### PR TITLE
Couchbase x

### PR DESCRIPTION
**Pull request by CCharlieLi**

### CODE REVIEW

**Comment by makara** [comment]
If you use a different name we are gonna need to maintain 2 repo or 2 branches. Could you save master to a different branch (say `couchbase3`) before you merge this?

**Comment by CCharlieLi** [comment]
Agreed, `couchbase3` branch can be a separate version and maintained separately if necessary. This is what I'm gonna do:
- create a new branch `couchbase3` from current `master`.
- merge `couchbaseX` into `master`, tag and push to npm.
- we change repo name as `loopback-connector-couchbaseX`.

@makara what do you think?

**Comment by makara** [comment]
OK.

BTW you removed the example and a lot of tests?

**Comment by CCharlieLi** [comment]
I removed example folder as datasource config has been described in readme, and it's annoying to maintain a LB project there.

I've merged test files.

**Comment by CCharlieLi** [comment]
@xavierchow you wanna take another pass?

**Comment by makara** [comment]
Hey you forgot `couchbase3` branch?

**Comment by CCharlieLi** [comment]
it's there now.

**Pull request merged**
