### PR TITLE
add jscs check

### PR DESCRIPTION
**Pull request by CCharlieLi**

### CODE REVIEW

**Comment by makara** [comment]
Thanks. However I feel that's too much change. Can we use a `.jscsrc` file (instead of the inline arguments) which allows some of them? For example:

```
{
    "preset": "airbnb",
    "requirePaddingNewLinesAfterBlocks": false,
    "requirePaddingNewLinesBeforeLineComments": false,
    "safeContextKeyword": ["self"]
}
```

**Comment by CCharlieLi** [comment]
Done.

**Comment by makara** [comment]
Thanks. Merging.

**Comment by makara** [comment]
@CCharlieLi You forgot the `.jscsrc` file. I guess it's ignored by `.gitignore`. Please add it.

**Pull request merged**
